### PR TITLE
Add configuration files for flake8.

### PR DESCRIPTION
**Pull request by hitblast**
This PR adds a `.flake8` at the root of the repository and removes the dependency from `.vscode/settings.json` to explicitly define the arguments to pass to flake8.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Looks good.

I spent some time earlier looking at Flake configuration.  

We can tailor the settings.json to provide the best configuration for working on this project.. something many projects I have seen do not do.

Approved this change for merging.

**Comment by hitblast** [comment]
> Looks good.
> 
> I spent some time earlier looking at Flake configuration.
> 
> We can tailor the settings.json to provide the best configuration for working on this project.. something many projects I have seen do not do.
> 
> Approved this change for merging.

Thanks for the approval!

**Comment by gbowne1** [comment]
You're welcome.  I really I would like to have at least one or two more devs doing review and approval..

I was hoping BenCos18 would be able to help out some more.

**Comment by gbowne1** [comment]
@hitblast I did not realize but there is a package [tholo/pytest-flake8](https://github.com/tholo/pytest-flake8)

My install added a .mypy_cache folder so there is this too: [ambv/flake8-mypy](https://github.com/ambv/flake8-mypy)

**Pull request merged**
