### PR TITLE
Added a basic exception handler and a new moderation command.

### PR DESCRIPTION
**Pull request by hitblast**
### Things changed:

- [x] Added a basic exception handler for handling errors raised by slash, user and message commands.
- [x] Added a new `/softban` command which softbans people to wipe their messages.

### CODE REVIEW

**Comment by hitblast** [comment]
@gbowne1 Could you please review my PR?

**Review by furtidev — COMMENTED** [review]
Looks good to me actually.

**Review by gbowne1 — COMMENTED** [review]
This looks good.  Looks like good cogs features.

**Review by gbowne1 — COMMENTED** [review]
I like this feature.

**Pull request merged**
