### PR TITLE
Adding  Documentation & fixes

### PR DESCRIPTION
**Pull request by gbowne1**
This PR #11 adds:

- [ ] Boilerplate TODO.md
- [ ] Boilerplate CHANGELOG.md 
- [ ] Boilerplate CONTRIBUTING.md

Fixes deprecated extensions for Python development

### CODE REVIEW

**Review by hitblast — APPROVED** [review]
Looking good to me!

**Comment by hitblast** [comment]
We might need to soon have a look at the workflows once again. Both of them failed in this PR. Other than that, it's looking pretty neat :D

**Comment by gbowne1** [comment]
Yes, they do fail. Might need a little work for them to run.

**Comment by gbowne1** [comment]
Thanks for the merge to main @hitblast

**Pull request merged**
