### PR TITLE
Added new cog, `/ban` slash command (+more) for starting off work on newer commands.

### PR DESCRIPTION
**Pull request by hitblast**
### Things changed:

- [x] Added a new **Moderation** cog which, for now, will start off with a new `/ban` slash command. It's pretty self-explanatory, just helps you ban people with an optional reason parameter.
- [x] Shortened type hints for command interactions.
- [x] Updated README.md with environment variable setup instructions.

### CODE REVIEW

**Comment by hitblast** [comment]
@gbowne1 Understood! 🚀

**Review by gbowne1 — APPROVED** [review]
Looks good.  Cant wait to test it.
I wanna work on the flask part.  Which zi am learning right now. Approving merge.

**Comment by hitblast** [comment]
> Looks good. Cant wait to test it.
> I wanna work on the flask part. Which zi am learning right now. Approving merge.

@gbowne1 If you want then I could work on the Flask part.

**Comment by gbowne1** [comment]
Yeah I was hoping to be able to get a flssk page going so we can have a dashboard some time this weekend.

Let me know what we need to do to connect the bot / app to the code.

**Comment by BenCos17** [comment]
yep feel free to ping me if you need anything 
Will likely not be on for a week or so though btw 

have some stuff i need to get done haha

**Pull request merged**
