### PR TITLE
Changed backend to disnake!

### PR DESCRIPTION
**Pull request by hitblast**
### Things changed:

- [x] Changed dependency from `discord` to `disnake` for enabling support for robust slash commands.
- [x] Fixed some broken syntax inside the **main.py** file.
- [x] Removed virtual environment from repository (malpractice).

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
I will approve this change, for further merge changes from Discord.py to disnake.

Looks like that would work fine.

I have not taled to @BenCos17 about it as I have not had time to.

**Review by gbowne1 — APPROVED** [review]
If you would like me to merge. Let me know.  I will approve this change.  

I need to review some more documentation.  I'm not fully set up for testing just yet.

I made some notes in `Issues`.

I'd like to stick with one linter, etc. so the configs need to be set up in .vscode/settings.json

**Comment by hitblast** [comment]
> If you would like me to merge. Let me know. I will approve this change.
> 
> I need to review some more documentation. I'm not fully set up for testing just yet.
> 
> I made some notes in `Issues`.
> 
> I'd like to stick with one linter, etc. so the configs need to be set up in .vscode/settings.json

Alright. Seems like every time I save a file on this repository using VSCode, a linter warning always keeps showing up for whatever reason :P

**Comment by gbowne1** [comment]
yeah, we've got to choose a linter and stick with it... and save the configs to settings.json.  I am sure it's the VSCode extension `Python` doing that.  

I don't know a great deal about Python code standardizaton so I expect our settings will reflect 'most' standards and we can improve from there.

I'm totally ok with whatever we choose to stick with.. just build a workflow from there.

That being said there are so many linters.  I don't know much about all of them but Pylint, Flake, black..

**Pull request merged**
