### PR TITLE
Added very basic help command and enabled Docker Compose.

### PR DESCRIPTION
**Pull request by hitblast**
### Things changed:

- [x] A new `/help` slash command can be accessed. This contains basic interactions for letting the user connect with the organization. These interactions include social links like GitHub and Twitter (not added yet).
- [x] The bot now supports multi-container operation using the [Docker Compose](https://docs.docker.com/compose/) platform. The root markdown (README.md) has also been updated to showcase this change.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
This is good.  I forgot to add the .md text

**Review by gbowne1 — APPROVED** [review]
I like this approach.  Need to have a good help.  The ones I have seen so far are not helpful at all.

**Review by gbowne1 — APPROVED** [review]
Need to work on the Docker stuff soon.
 Feel like this is a good step forward.

**Comment by hitblast** [comment]
@gbowne1 Thanks for your review! Will definitely look deeper into this.

**Comment by gbowne1** [comment]
Added the bot App to Discord but have no idea how the rest works. 

Yes I would like to create at least one container.  One for development of group projects.  Not sure yet on others.  It could possibly be an administrative and a possible 3rd could run the bots for youtube, twitch, discord.  I hear YT allows bots now.

Oh and do not add AmigaGod to reviews.

**Comment by gbowne1** [comment]
@hitblast Added docker repository this morning.

**Pull request merged**
