### PR TITLE
Add /mkinvite and /invites

### PR DESCRIPTION
**Pull request by Ba3a-G**
## Added new commands

- /invite: creates a new invite
- /listinvites: lists all the invite codes

### CODE REVIEW

**Review by furtidev — CHANGES_REQUESTED** [review]
Hi, I guess `/listinvites` could just be renamed to `/invites` as it makes more sense and it's smaller.

**Comment by Ba3a-G** [comment]
Then we should probably rename `/invite` too, `/invite` and `/invites` might get confusing.

**Comment by gbowne1** [comment]
I would refrain from doing too much overlap or redundant commands

**Comment by furtidev** [comment]
> Then we should probably rename `/invite` too, `/invite` and `/invites` might get confusing.
@Ba3a-G How about `/mkinvite` or something similar? 🤔

**Comment by furtidev** [comment]
> I would refrain from doing too much overlap or redundant commands

@gbowne1  I personally think the invite commands are pretty helpful since it's slow to actually work with them using Discord's GUI. What's your opinion?

**Comment by Ba3a-G** [comment]
> I would refrain from doing too much overlap or redundant commands

We personally use invite commands often so thought it might be useful.
Should I go ahead with this?

**Review by furtidev — APPROVED** [review]
I approve this for now. Let's see what others say.

**Comment by gbowne1** [comment]
@taotnpwaft/members

I need to make an official statment about commit, push, reveiew and merges.

Our rules are that we require a minimum of two reviews before merge to main.

There/these are contributing docs in the Metadata project:

https://github.com/taotnpwaft/Metadata/CONTRIBUTING.md

I believe theres also a developer guide too.

Also anyone who makes more than 2 significant changes needs to be added as a taotnpwaft member.

I am thinking about adding taotnpwaft develper stuff to the main website.

You can help make these rules finalized or better by PR to the rules.

**Comment by gbowne1** [comment]
We typically have had very few invires and not much traffic up to this point.

We actually have lost more members in Discord than we have kept.

The number we have lost in the 2-3 year period is around 60 members of Discord.  We have only gained a dozen or so in the past year so we need to get on a membership drive for Discord so we can get the 60+ back.

I am considering making a Supoort or Developer role in our Discord just for the Discord maintenance for anyone doing Discord development.

The invite link is in the main page of this org overview here on GH.

If you would like to make this a thing let me know.  @hitblast or I can add roles.

**Review by gbowne1 — APPROVED** [review]
This change looks good.  Looks like the runner failed?

**Comment by Ba3a-G** [comment]
> The invite link is in the main page of this org overview here on GH.

For sure! I have joined the server, I'll ask @hitblast for the role.

> This change looks good. Looks like the runner failed?

All greens! 🙂

**Comment by gbowne1** [comment]
I can add roles too I am also pretty sure that AmigaGod may give roles too.. 

I can make a developer role happen though as long as there is some consensus.

**Review by hitblast — APPROVED** [review]
Banger PR!

**Pull request merged**
